
on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ie-bank-backend.yml'

env:
  BACKEND_WEBAPP_DEV: sbrenner-asc-backend
  

jobs:
  test:
    
    runs-on: ubuntu-latest
    env:
      ENV: Development
      ACR_NAME_DEV: sbrenneracr

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./backend

      - name: Lint with flake8
        run: |
          pip install flake8 pytest
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        working-directory: ./backend  

      - name: Test with pytest
        run: |
            python -m pytest --cov=iebank_api -v
        working-directory: ./backend
        
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
            name: python-app
            path: |
              .
